version: '3.4'
services:
    simulator:
        image: ${DOCKER_REGISTRY-}toyrobotsimulator
        build:
            context: .
            dockerfile: Simulator\Dockerfile
        container_name: "simulator"
    test:
        image: ${DOCKER_REGISTRY-}toyrobotsimulatortest
        build:
            context: .
            dockerfile: ToyRobotSimulator.UnitTest\Dockerfile
        container_name: "test"
        